# Generated by Django 2.0.2 on 2018-02-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodservice',
            options={'ordering': ['-id'], 'verbose_name': 'Заведение общественного питания', 'verbose_name_plural': 'Заведения общественного питания'},
        ),
    ]
